package me.Logicism.OpenRGB4J.openrgb;

public enum OpenRGBPacket {
    NET_PACKET_ID_REQUEST_CONTROLLER_COUNT(0),
    NET_PACKET_ID_REQUEST_CONTROLLER_DATA(1),
    NET_PACKET_ID_REQUEST_PROTOCOL_VERSION(40),
    NET_PACKET_ID_SET_CLIENT_NAME(50),
    NET_PACKET_ID_REQUEST_PROFILE_LIST(150),
    NET_PACKET_ID_REQUEST_SAVE_PROFILE(151),
    NET_PACKET_ID_REQUEST_LOAD_PROFILE(152),
    NET_PACKET_ID_REQUEST_DELETE_PROFILE(153),
    NET_PACKET_ID_REQUEST_PLUGIN_LIST(200),
    NET_PACKET_ID_PLUGIN_SPECIFIC(201),
    NET_PACKET_ID_RGBCONTROLLER_RESIZEZONE(1000),
    NET_PACKET_ID_RGBCONTROLLER_CLEARSEGMENTS(1001),
    NET_PACKET_ID_RGBCONTROLLER_ADDSEGMENT(1002),
    NET_PACKET_ID_RGBCONTROLLER_UPDATELEDS(1050),
    NET_PACKET_ID_RGBCONTROLLER_UPDATEZONELEDS(1051),
    NET_PACKET_ID_RGBCONTROLLER_UPDATESINGLELED(1052),
    NET_PACKET_ID_RGBCONTROLLER_SETCUSTOMMODE(1100),
    NET_PACKET_ID_RGBCONTROLLER_UPDATEMODE(1101),
    NET_PACKET_ID_RGBCONTROLLER_SAVEMODE(1102);

    private int packetID;

    OpenRGBPacket(int packetID) {
        this.packetID = packetID;
    }

    public int getPacketID() {
        return packetID;
    }
}
